version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "17:30"
    timezone: Europe/London
  ignore:
  - dependency-name: symfony/string
    versions:
    - 5.2.4
    - 5.2.6
